### ISSUE TITLE
Headings hidden behind survey banner after clicking table of contents

### ISSUE THREAD

**Issue by zarino** [mysociety/fixmyblock-wordpress#48]
We need to add a vertical offset for headings with an [id], so they don’t disappear behind the survey banner when jumped to from the table of contents.

Two ways I can think of doing this:

## Padding and negative margin

```scss
h1, h2, h3, h4, h5, h6 {
    &[id] {
        padding-top: 5em;
        margin-top: -3.5em; // emulate a 1.5em default margin
    }
}
```

Drawbacks:

* Need to make sure the "emulated" margin is right for each size of heading.
* Not sure how this will work with the `:first-child { margin-top: 0 }` we’ve got set on headings (IIRC?)
* Will look broken if headings have a background colour.

## Child anchor

```php
function move_heading_id_to_child_anchor( $block_content, $block ) {
    if ( $block['blockName'] === 'core/heading' ) {
        // We already have a `extract_heading_info` function in `functions-table-of-contents.php`
        $b = extract_heading_info($block);
        return sprintf(
            '<h%s><a id="%s" class="fragment"></a>%s</h%s>',
            $b['level'],
            $b['id'],
            $b['text'], // TODO!
            $b['level']
        );
    }
    return $block_content;
}
add_filter( 'render_block', 'move_heading_id_to_child_anchor', 10, 2 );
```

```scss
.fragment {
    display: block;
    transform: translate(0, -100px);
}
```

Drawbacks:

* Bit more complicated.
* Need to amend the `['text']` bit, so that the entire HTML contents of the original block is returned (rather than the `wp_strip_all_tags` version).
